CREATE TABLE IF NOT EXISTS activities (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    text VARCHAR(500) NOT NULL,
    time_label VARCHAR(255) NOT NULL,
    type VARCHAR(255) NOT NULL
);

CREATE TABLE IF NOT EXISTS appointments (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    appointment_date DATE NOT NULL,
    doctor_name VARCHAR(255) NOT NULL,
    patient_name VARCHAR(255) NOT NULL,
    reason VARCHAR(1000) NOT NULL,
    status VARCHAR(255) NOT NULL,
    appointment_time VARCHAR(255) NOT NULL
);

CREATE TABLE IF NOT EXISTS beds (
    id VARCHAR(255) PRIMARY KEY,
    bed_number VARCHAR(255) NOT NULL,
    occupied_by_id BIGINT,
    status VARCHAR(255) NOT NULL,
    ward VARCHAR(255) NOT NULL
);

CREATE TABLE IF NOT EXISTS doctors (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    contact VARCHAR(255) NOT NULL,
    email VARCHAR(255) NOT NULL,
    experience VARCHAR(255) NOT NULL,
    name VARCHAR(255) NOT NULL,
    patients_count INTEGER NOT NULL,
    spec VARCHAR(255) NOT NULL,
    status VARCHAR(255) NOT NULL
);

CREATE TABLE IF NOT EXISTS patients (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    age INTEGER NOT NULL,
    bed_id VARCHAR(255),
    blood_group VARCHAR(255) NOT NULL,
    check_in_date DATE NOT NULL,
    contact VARCHAR(255) NOT NULL,
    department VARCHAR(255) NOT NULL,
    diagnosis VARCHAR(2000),
    doctor_name VARCHAR(255) NOT NULL,
    gender VARCHAR(255) NOT NULL,
    name VARCHAR(255) NOT NULL,
    status VARCHAR(255) NOT NULL,
    blood_pressure VARCHAR(255) NOT NULL,
    pulse_bpm INTEGER NOT NULL,
    oxygen_saturation INTEGER NOT NULL,
    temperature VARCHAR(255) NOT NULL
);

CREATE TABLE IF NOT EXISTS patient_prescriptions (
    patient_id BIGINT NOT NULL,
    prescription_text VARCHAR(1000) NOT NULL,
    CONSTRAINT fk_patient_prescriptions_patient
        FOREIGN KEY (patient_id) REFERENCES patients(id)
);
